interface File {
    created: number;
    display_as_bot: boolean;
    editable: boolean;
    external_type: string;
    filetype: string;
    has_rich_preview: boolean;
    id: string;
    is_external: boolean;
    is_public: boolean;
    is_starred: boolean;
    mimetype: string;
    mode: string;
    name: string;
    original_h: number;
    original_w: number;
    permalink: string;
    permalink_public: string;
    pretty_type: string;
    public_url_shared: boolean;
    size: number;
    thumb_160: string;
    thumb_360: string;
    thumb_360_h: number;
    thumb_360_w: number;
    thumb_480: string;
    thumb_480_h: number;
    thumb_480_w: number;
    thumb_64: string;
    thumb_80: string;
    thumb_tiny: string;
    timestamp: number;
    title: string;
    url_private: string;
    url_private_download: string;
    user: string;
    username: string;
}

export type { File };
